usuario_homepage:
    path:     /hello/{name}
    defaults: { _controller: UsuarioBundle:Default:index }

usuario_login:
 path: /login
 defaults: { _controller:UsuarioBundle:Security:login }
 
usuario_registro:
 path: /registro
 defaults: { _controller:UsuarioBundle:Security:registro }

usuario_login_check:
 path: /login_check
 
usuario_logout:
 path: /logout