_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

_welcome:
<<<<<<< HEAD
    path: /
    defaults: { _controller:AppBundle:Default:index }

_welcomeBase:
    path: /home
    defaults: { _controller:AppBundle:Welcome:home }
=======
    path: /login
    defaults: { _controller:AppBundle:Security:login }
>>>>>>> 697eb5f79e33a2737016cb2a69ad138b4dd9849b
